# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sname', models.CharField(blank=True, max_length=64, null=True)),
                ('logo', models.CharField(blank=True, max_length=64, null=True)),
                ('rank', models.IntegerField(default=1)),
                ('status', models.CharField(default='A', max_length=2)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('area', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'community',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_version', models.CharField(max_length=128)),
                ('android_url', models.CharField(max_length=128)),
                ('android_notes', models.CharField(max_length=128)),
                ('android_radio', models.IntegerField()),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('sname', models.CharField(blank=True, max_length=64, null=True)),
                ('des', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u89c4\u683cJSON')),
                ('rank', models.IntegerField(default=1)),
                ('status', models.CharField(default='A', max_length=2)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.IntegerField(verbose_name='\u5e93\u5b58\u6570')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appApi.Category')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appApi.Community')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Smsmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16)),
                ('content', models.CharField(max_length=256)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'smsmessage',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('pswd', models.CharField(max_length=32)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('sex', models.IntegerField()),
                ('signature', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('addfrom', models.CharField(max_length=16)),
                ('last_login_time', models.DateTimeField()),
                ('status', models.CharField(max_length=4)),
                ('faceimg_s', models.CharField(max_length=64)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appApi.Community')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
