# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('area', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'community',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('pswd', models.CharField(max_length=32)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('yongjin', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('signature', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('addfrom', models.CharField(max_length=16)),
                ('last_login_time', models.DateTimeField()),
                ('status', models.CharField(max_length=4)),
                ('faceimg_s', models.CharField(max_length=64)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appApi.Community')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
