# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smsmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('checked', models.IntegerField()),
                ('message', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'smsmessage',
            },
        ),
    ]
