# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0002_smsmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='name',
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='phone',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='source',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
